version: '4.37.1'
services:
 nest_app:
    build:
       context: .
       dockerfile: Docker-file
    ports:
       - 3333:3333  
    depends_on:
       - dev-db
    environment:
        - JWT_SECRET=${JWT_SECRET}
        - DATABASE_URL=${DATABASE_URL}  
    volumes:
      - ./node_modules:/app/node_modules
      - ./prisma:/app/prisma    
    networks:
     - MW11






 dev-db:
   image: postgres:latest
   ports:
       - 5432:5432
   environment:
        POSTGRES_USER: ${POSTGRES_USER}  
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
   networks:
       - MW11   

networks:
   MW11:       

    